builds:
- main: ./cmd/bitbrew
  env:
  - CGO_ENABLED=0
  - GO111MODULE=on
  goos:
    - linux
    - darwin
  goarch:
    - 386
    - amd64
    - arm
    - arm64
before:
  hooks:
    - go mod download
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^Fix'
    - '^Refactor'
brew:
  github:
    owner: micnncim
    name: homebrew-tap
  folder: Formula
  description: "bitbrew: BitBar plugin manager"
  homepage: "https://github.com/micnncim/bitbrew"
  install: |
    bin.install "bitbrew"
  test: |
    system "#{bin}/bitbrew"
