version: 2.1
executors:
  default:
    docker:
      - image: circleci/golang:1.12
        environment:
          GO111MODULE: "on"
    working_directory: /go/src/github.com/micnncim/bitbrew
commands:
  restore_dep:
    steps:
      - restore_cache:
          keys:
            - go-mod-{{ checksum "go.sum" }}
  save_dep:
    steps:
      - save_cache:
          key: go-mod-{{ checksum "go.sum" }}
          paths:
            - /go/pkg/mod/cache
  install_dep:
    steps:
      - run:
          command: go mod download
jobs:
  build:
    executor:
      name: default
    steps:
      - checkout
      - restore_dep
      - install_dep
      - save_dep
      - run:
          name: Run test and collect coverage
          command: |
            make coverage
            bash <(curl -s https://codecov.io/bash)
      - run:
          name: Run linter
          command: |
            go get -u github.com/haya14busa/reviewdog/cmd/reviewdog
            go get -u golang.org/x/lint/golint
            make reviewdog
  release:
    executor:
      name: default
    steps:
      - checkout
      - restore_dep
      - install_dep
      - run:
          name: Release by GoReleaser
          command: curl -sL https://git.io/goreleaser | bash

  workflows:
    build_and_release:
      jobs:
        - build:
            filters:
              tags:
                only: /.*/
        - release:
            requires:
              - build
            filters:
              tags:
                only: /.*/
              branches:
                ignore: /.*/
